package gt.edu.umg.labgui;

import javax.swing.JOptionPane;

/**
 * @author Luis Alonzo
 */

public class Principal extends javax.swing.JFrame {

    private Calculadora calculadora;
    
    double num1 = 0.0;
    double num2 = 0.0;
    double resultado = 0.0;
    
    public Principal() {
        initComponents();
        calculadora = new Calculadora("Casio", "FX-981");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMensaje = new javax.swing.JPanel();
        txtNum1 = new javax.swing.JLabel();
        txtNum2 = new javax.swing.JLabel();
        tfNum1 = new javax.swing.JTextField();
        tfNum2 = new javax.swing.JTextField();
        panelEscritura = new javax.swing.JPanel();
        btnDividir = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtResultado = new javax.swing.JLabel();
        txtInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Principal");
        setBackground(new java.awt.Color(102, 255, 102));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMensaje.setBackground(new java.awt.Color(244, 253, 251));
        panelMensaje.setPreferredSize(new java.awt.Dimension(340, 150));
        panelMensaje.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNum1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        txtNum1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtNum1.setText("Primer Número:");
        panelMensaje.add(txtNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 40));

        txtNum2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        txtNum2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtNum2.setText("Segundo Número:");
        panelMensaje.add(txtNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 160, 40));

        tfNum1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tfNum1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        panelMensaje.add(tfNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 32, 140, 40));

        tfNum2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tfNum2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        panelMensaje.add(tfNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 112, 140, 40));

        getContentPane().add(panelMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 190));

        panelEscritura.setBackground(new java.awt.Color(152, 203, 180));
        panelEscritura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDividir.setBackground(new java.awt.Color(123, 160, 152));
        btnDividir.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnDividir.setForeground(new java.awt.Color(255, 252, 232));
        btnDividir.setText("Dividir");
        btnDividir.setBorder(null);
        btnDividir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });
        panelEscritura.add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 100, 80));

        btnSumar.setBackground(new java.awt.Color(123, 160, 152));
        btnSumar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnSumar.setForeground(new java.awt.Color(255, 252, 232));
        btnSumar.setText("Sumar");
        btnSumar.setBorder(null);
        btnSumar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });
        panelEscritura.add(btnSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 100, 80));

        btnRestar.setBackground(new java.awt.Color(123, 160, 152));
        btnRestar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnRestar.setForeground(new java.awt.Color(255, 252, 232));
        btnRestar.setText("Restar");
        btnRestar.setBorder(null);
        btnRestar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });
        panelEscritura.add(btnRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 100, 80));

        btnMultiplicar.setBackground(new java.awt.Color(123, 160, 152));
        btnMultiplicar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnMultiplicar.setForeground(new java.awt.Color(255, 252, 232));
        btnMultiplicar.setText("Multiplicar");
        btnMultiplicar.setBorder(null);
        btnMultiplicar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });
        panelEscritura.add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 100, 80));

        jPanel1.setBackground(new java.awt.Color(255, 252, 232));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        txtResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 60));

        txtInfo.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        txtInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtInfo.setText("Nombre:Luis Alonzo    Carné:2690-20-348");
        jPanel1.add(txtInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 340, -1));

        panelEscritura.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 340, 100));

        getContentPane().add(panelEscritura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 340, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        try{
           numeros();
           
           this.resultado = calculadora.dividir(this.num1, this.num2);
           
           this.txtResultado.setText(Double.toString(this.resultado));
        }catch(Exception e){
            mensaje();
        }
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        try{
           numeros();
           
//           this.resultado = this.num1 + this.num2;
           this.txtResultado.setText(Double.toString(calculadora.sumar(this.num1,this.num2)));
        }catch(Exception e){
            mensaje();
        }
    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        try{
           numeros();
           
           this.resultado = calculadora.restar(this.num1, this.num2);
           
           this.txtResultado.setText(Double.toString(this.resultado));
        }catch(Exception e){
            mensaje();
        }
    }//GEN-LAST:event_btnRestarActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        try{
           numeros();
           
           this.resultado = calculadora.multiplicar(this.num1, this.num2);
           
           this.txtResultado.setText(Double.toString(this.resultado));
        }catch(Exception e){
            mensaje();
        }
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    public void numeros(){
        this.num1 = Double.parseDouble(this.tfNum1.getText());
        this.num2 = Double.parseDouble(this.tfNum2.getText());
    }
    
    public void mensaje(){
        JOptionPane.showMessageDialog(null, "Los campos no pueden ir vacios.\nNi contener letras.", "Advertencia", 0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelEscritura;
    private javax.swing.JPanel panelMensaje;
    private javax.swing.JTextField tfNum1;
    private javax.swing.JTextField tfNum2;
    private javax.swing.JLabel txtInfo;
    private javax.swing.JLabel txtNum1;
    private javax.swing.JLabel txtNum2;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables
}
